### ISSUE TITLE
Can't generate HTML by `marge` from the merged json.

### ISSUE THREAD

**Issue by huyvanvu** [Antontelesh/mochawesome-merge#1]
When running the command `node_modules/.bin/marge mergedReport.json --reportDir report`, getting these errors:
`

- Invalid value undefined supplied to /suites/suites/0/tests/0/timedOut: Boolean
- Invalid value undefined supplied to /suites/suites/0/tests/1/timedOut: Boolean
- Invalid value undefined supplied to /suites/suites/1/tests/0/timedOut: Boolean
- Invalid value undefined supplied to /suites/suites/1/tests/1/timedOut: Boolean
-   Invalid value undefined supplied to /suites/root: Boolean
-   Invalid value undefined supplied to /suites/_timeout: Number
-   Invalid value undefined supplied to /suites/passes: Array<UUID>
-   Invalid value undefined supplied to /suites/failures: Array<UUID>
-   Invalid value undefined supplied to /suites/pending: Array<UUID>
-   Invalid value undefined supplied to /suites/skipped: Array<UUID>
-   Invalid value undefined supplied to /copyrightYear: Number

`
It seems that fields are missing from the json report.

**Comment by Antontelesh** [comment]
Yes, this is a problem of marge or mochawesome. If you try the same over one of the mochawesome reports, you will get the same set of errors.

That’s because marge expects `timedOut` to exist while mochawesome does not generate it.

**Comment by Antontelesh** [comment]
This validation happens only when running `marge` as a CLI. If you run it from a JavaScript it will generate you the HTML report correctly:

```javascript
const marge = require('mochawesome-report-generator')
const { merge } = require('mochawesome-merge')
merge().then(json => marge.create())
```

This works for me

**Comment by Antontelesh** [comment]
I will keep this issue open to address properties other than `timedOut`

**Comment by Antontelesh** [comment]
Fixed in v1.0.3

Also, here's the link to the original issue: adamgruber/mochawesome-report-generator#88

**Comment by badgeek** [comment]
still happening in     "mochawesome-merge": "^1.0.4",

**Comment by Antontelesh** [comment]
Happening only for `timedOut` or other properties as well?

**Comment by badgeek** [comment]
only for timedOut, im using cypress

**Comment by Antontelesh** [comment]
For `timedOut` please refer to adamgruber/mochawesome-report-generator#88

**Comment by huyvanvu** [comment]
> This validation happens only when running `marge` as a CLI. If you run it from a JavaScript it will generate you the HTML report correctly:
> 
> ```js
> const marge = require('mochawesome-report-generator')
> const { merge } = require('mochawesome-merge')
> merge().then(json => marge.create(json))
> ```
> 
> This works for me

This solution works well for me. Thanks heap.

**Comment by kumangxxx** [comment]
merge generate this JSON

```
{
  "stats": {
    "suites": 0,
    "tests": 0,
    "passes": 0,
    "pending": 0,
    "failures": 0,
    "start": "2019-02-18T03:59:07.579Z",
    "end": "2019-02-18T03:59:07.579Z",
    "duration": 0,
    "testsRegistered": 0,
    "passPercent": null,
    "pendingPercent": null,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false,
    "passPercentClass": "warning",
    "pendingPercentClass": "danger"
  },
  "suites": {
    "uuid": "0aa59bd0-4a8f-4674-b85b-44fc67a37257",
    "tests": [],
    "suites": [],
    "duration": 0,
    "root": true,
    "rootEmpty": true,
    "title": "",
    "fullFile": "",
    "file": "",
    "beforeHooks": [],
    "afterHooks": [],
    "passes": [],
    "failures": [],
    "pending": [],
    "skipped": [],
    "_timeout": 2000
  },
  "copyrightYear": 2019
}
```

using marge throws error bcause passPercent is null

**Comment by Antontelesh** [comment]
@kumangxxx thank you for reporting this. Could you create a new issue with reproduction steps? Also, PRs are welcome

**Comment by r1y4h** [comment]
@kumangxxx 

I also have the same issue. In my case I change mochawesome output filenames but mochawesome-merge expects this file format: 

mochawesome*.json

**Comment by Antontelesh** [comment]
@r1y4h why do you change the filenames?

**Comment by r1y4h** [comment]
I did it before I realize that cypress splits the test results and found out that your code is expecting mochawesome*.json pattern.

Now I am just using the default filename and just set my desired file for merged file.

**Comment by monikajastrzebska** [comment]
Hi! I also have problem with 'passPercent is null' @kumangxxx have you solution this problem?
