### ISSUE TITLE
Report filenames should be configurable

### ISSUE THREAD

**Issue by MarS919** [Antontelesh/mochawesome-merge#10]
First of all, thanks for mochawesome and this super-handy merge tool!

I have a little improvement suggestion: mochawesome-merge should have a configurable report filename (like mochawesome has env variable `MOCHAWESOME_REPORTFILENAME` and argument `reportFilename`) instead of being hardcoded to '`mochawesome*.json`'.

Currently, if I set env variable `MOCHAWESOME_REPORTFILENAME`, mochawesome-merge will not be able to find the reports.

**Comment by Antontelesh** [comment]
Hey @MarS919 

This would be a good improvement to the library.
What are the reasons you rename your intermediate report filenames?

**Comment by MarS919** [comment]
I'm testing several projects and therefore I add the project name to the report file name for clarity. This way, they are also useful before being merged.

**Comment by Antontelesh** [comment]
A nice use-case.

Personally I don't have an idea of how to implement this keeping in mind that `mochawesome*.json` is just a glob pattern.
We would need some kind of `reportFilename → glob` transformation for it to work.

@MarS919 I would love if you tried that yourself and opened a PR with the changes.

**Comment by Antontelesh** [comment]
I would like to allow users to specify the glob pattern for source reports. Something like this:

```
npx mochawesome-merge ./reports/report* > final.json
```

@MarS919 and others, what do you think about this API?

**Comment by YOU54F** [comment]
@Antontelesh sounds like a good plan,

I would just ensure that when the glob pattern is picked up, it is only applied against `*.json` files just in case there is any other files in the folder.

This is the line in your code

https://github.com/Antontelesh/mochawesome-merge/blob/95f272b3d1e9cb8aecf3c2f3b06793deeca25b6c/lib/index.js#L37

I use a function that can get all files in a folder with a specific extension

Here is the line when I call my getFiles function 

https://github.com/YOU54F/cypress-slack-reporter/blob/0579466b884aba48662143246e5e0796770c3bc0/src/slack/slack-alert.ts#L304

and the function to retrieve files from a folder (it will recursively search through folders, which allows me to pickup screenshots and videos in nested folders)

https://github.com/YOU54F/cypress-slack-reporter/blob/0579466b884aba48662143246e5e0796770c3bc0/src/slack/slack-alert.ts#L267

**Comment by Antontelesh** [comment]
@YOU54F is there any package that can do this for us? How is it done in popular packages that accept globs?

I’m asking just because I don’t have much experience working with fs. And if there is a proven tested solution to this I would tend to use it rather than creating it from scratch.

**Comment by YOU54F** [comment]
I’m not sure but there will be something. Will just need some digging. 

Would be nice to not to reinvent the wheel! If you do find something, I’d probably incorporate in my package as long as it’s not got too many dependencies. I’ve got a few tests on my function and it has been working well, but always nice to have something that has been well used and battle tested. I’ll keep my eyes peeled

**Comment by YOU54F** [comment]
@Antontelesh 

this looks decent - https://github.com/mauriciovigolo/file-matcher and only has one dependency (micromatch)

written in typescript too =D

**Comment by Antontelesh** [comment]
I would tend to use something like [globby](https://www.npmjs.com/package/globby)

**Comment by YOU54F** [comment]
Globby looks nice mate, and at 14 million downloads a week, you can’t really go wrong!

**Comment by ArnaudBDev** [comment]
Hi Anton,

Thanks for your work on the plugin. Today I lost time to understand that's report should be name "mochawesome*.json". 
I had to check inside the code the root cause of my error (TypeError: Cannot read property 'meta' of undefined).
Could you make a move to have manage better this error? I had a different name for my report as mochwesome allow it.
Or just update the README with the requirements.
Same thing for the compatibility between mochawesome versions ;)

Thanks a lot,

**Comment by vrodnyanskiy** [comment]
Hi, 
When I try to merge reports I'm getting:
ERROR: Failed to merge reports

TypeError: Cannot read property 'filter' of undefined
    at report (/cypress/node_modules/mochawesome-merge/lib/index.js:44:18)
    at Array.map (<anonymous>)
    at items (/cypress/node_modules/mochawesome-merge/lib/utils.js:3:46)
    at merge (/cypress/node_modules/mochawesome-merge/lib/index.js:57:18)

The error does not make sense to me.
Any help plz.
The command I use:
npx mochawesome-merge reports > mochawesome.json

There are my json reports: 
[mochawesome-report.zip](https://github.com/Antontelesh/mochawesome-merge/files/3475150/mochawesome-report.zip)

**Comment by ojizero** [comment]
@Antontelesh are there any updates regarding this issue? If not I'd like to jump in and try to fix it!

**Comment by Antontelesh** [comment]
@ojizero, the only way to make it happen is to open a PR

**Comment by ojizero** [comment]
Alright 👍 just to confirm your suggestion was to use glob patterns as a first argument correct? i.e. `npx mochawesome-merge /some/glob/pattern` what about the old behaiour (using `reportDir` and `rootDir` options) should they be kept (backward compatibility) or just dropped in favour of the new API?

**Comment by ojizero** [comment]
Also I see that the CI for it is run on Node 8, [which reaches EOL later this month](https://github.com/nodejs/Release), I'm thinking of bumping that on my way is it alright? @Antontelesh

**Comment by Antontelesh** [comment]
I would drop support for `rootDir` and `reportDir` and replaced them with the glob pattern.

Regarding the node version, I would highly appreciate the update, but would love if you do it in a separate PR, so that we could merge it before making breaking changes.

Thank you for expressing the wish to help here. I will think about integrating [All Contributors](https://allcontributors.org/) into the project to recognize your help, guys.

**Comment by ojizero** [comment]
@Antontelesh okk will do so, one more thing do you plan to keep the enginers directive stating support for `node >= 8.6.0` ? If we plan to change that to reflect the EOL of Node 8 then maybe we can merge both together (since both are breaking changes that way).

**Comment by Antontelesh** [comment]
Sounds good to me. Let’s keep them in one release

**Comment by ojizero** [comment]
@Antontelesh just opened #32 can you check it please

**Comment by nani554** [comment]
Still facing this issue, when i have custom name
Below is the command iam using
`mochawesome-merge` --reportDir cypress/reports/mocha-reports/ > `cypress/reports/mocha-reports/merged/report.json`

Could you please give me correct glob syntax(command) which has resolved this issue

**Comment by Antontelesh** [comment]
@nani554 please take a look at #39 
There is an example in comments
