### ISSUE TITLE
Breaking changes in mochawesome v4.0

### ISSUE THREAD

**Issue by YOU54F** [Antontelesh/mochawesome-merge#12]
Hey up @Antontelesh 

[V4](https://github.com/adamgruber/mochawesome/releases/tag/4.0.0) of [mochawesome](https://github.com/adamgruber/mochawesome) has just been released, it contains some breaking changes, that will need catering for. You can make changes backwards compatible by reading the version from mochawesome’s package.json and reading from the old or new report structure. (see [here](https://github.com/YOU54F/cypress-multi-reporters/blob/4df5c1d8b195e1ac4aa7c44117166ffee9151a0d/lib/MultiReporters.js#L20) for an example)

Breaking changes from the change log as follows

```
Breaking changes to JSON data structure
Renamed allSuites to results and made it an array of suites
Removed isRoot property from cleaned tests (only suites can be a root)
Removed class-related stats (passPercentClass, pendingPercentClass)
Added uuid to suites
Removed rounding of passPercent and pendingPercent
Removed copyrightYear property
Added new meta property to track info about the test run (useful for debugging)
```

**Comment by Antontelesh** [comment]
Thank you for your effort, @YOU54F

I would happily accept PRs for this change.
Or in some time will just release a major version of mochawesome-merge compatible with mochawesome@4

**Comment by YOU54F** [comment]
I've created a fork so I'll see what I can rustle up when I get some time 👍

**Comment by Antontelesh** [comment]
@YOU54F I have created a PR for supporting mochawesome@4.

Please, take a look, I need your review first. It would be nice if you also tried to pull the branch and run the package locally. I don't use mochawesome@4 yet, so cannot run it over a real project.

**Comment by YOU54F** [comment]
Brilliant, I have a few projects with renovate setup, that have pulled in the latest mochawesome version, so will be able to test against them.

Will be able to do this later on this evening, and I will report back.

Thanks for your quick work on this!

**Comment by YOU54F** [comment]
CI build kicked off

https://github.com/YOU54F/cypress-slack-reporter/pull/97/files

have tested locally and looks good!

**Comment by YOU54F** [comment]
CI passes

circle ci - https://circleci.com/gh/YOU54F/cypress-slack-reporter/295

**Comment by Antontelesh** [comment]
Thank you for such a quick feedback! I have merged the PR. The new version should be released in a few seconds.

**Comment by YOU54F** [comment]
Great work @Antontelesh 🤙

**Comment by deane187** [comment]
Hi Guys,

Awesome work and great response time!

`npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json`
I get the following error when i try to merge:
```
ERROR: Failed to merge reports

TypeError: Cannot read property 'meta' of undefined
    at merge (/Users/deane.rousseau/Developer/automated-tests/node_modules/mochawesome-merge/lib/index.js:59:22)
deane-rousseau% npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json
ERROR: Failed to merge reports

TypeError: Cannot read property 'meta' of undefined
    at merge (/Users/deane.rousseau/Developer/automated-tests/node_modules/mochawesome-merge/lib/index.js:59:22)
```
These are my dependencies:
```
"devDependencies": {
    "crypto": "^1.0.1",
    "cypress": "^3.3.1",
    "cypress-dark": "^1.7.13",
    "cypress-multi-reporters": "^1.1.20",
    "cypress-slack-reporter": "^0.3.1",
    "cypress-xpath": "^1.4.0",
    "dotenv-safe": "^6.1.0",
    "mocha": "^6.1.4",
    "mocha-junit-reporter": "^1.21.0",
    "mocha-junit-reporters": "^1.23.6",
    "mocha-multi-reporters": "^1.1.7",
    "mocha-slack-reporter": "0.0.8",
    "mochawesome": "^4.0.0",
    "mochawesome-merge": "^2.0.0",
    "mochawesome-report-generator": "^4.0.0",
    "moment": "^2.24.0",
    "twit": "^2.2.11",
    "twitter": "^1.7.1",
    "util.promisify": "^1.0.0"
  }
```
Theres also a warning: `npm WARN cypress-slack-reporter@0.3.1 requires a peer of mochawesome@^3.1.1 but none is installed. You must install peer dependencies yourself.`

**Comment by YOU54F** [comment]
FYI, looking at your deps, you don’t need mocha-multi-reporters, or mocha-junit-reporter for mocha 6 support. Cypress-multi-reporters and mocha-junit-reporters are sufficient. Make sure you grab the latest versions too 🤙
