### ISSUE TITLE
Error when running mochawesome-merge (Invalid value)

### ISSUE THREAD

**Issue by ezra-m** [Antontelesh/mochawesome-merge#16]
When running mochawesome-merge I get the following results:

```
Invalid value "warning" supplied to /stats/passPercentClass: Nil
  Invalid value "danger" supplied to /stats/pendingPercentClass: Nil
  Invalid value undefined supplied to /results: Array<Suite>
  Invalid value {
...
// json test results
...
}
```

The individual json files and html reports are being generated, but nothing is being merged.

dev dependency info:
```
"cypress": "^3.3.1",
"eslint": "^5.9.0",
"mocha": "^5.2.0",
"mochawesome": "^3.1.2",
"mochawesome-merge": "^1.0.7",
"mochawesome-report-generator": "^3.1.5"
```
I have successfully used the node script method to run mochawesome-merge as given [here](http://antontelesh.github.io/testing/2019/02/04/mochawesome-merge.html) but I would prefer to use the CLI if possible.

Any help is appreciated, thanks.

**Comment by deane187** [comment]
Hey @ezra-m 

Have a look at my dev dependencies:
```
"devDependencies": {
    "crypto": "^1.0.1",
    "cypress": "^3.3.1",
    "cypress-dark": "^1.7.13",
    "cypress-multi-reporters": "^1.1.20",
    "cypress-slack-reporter": "^0.4.0",
    "cypress-xpath": "^1.4.0",
    "dotenv-safe": "^6.1.0",
    "mocha": "^6.1.4",
    "mocha-junit-reporters": "^1.23.6",
    "mocha-slack-reporter": "0.0.8",
    "mochawesome": "^4.0.0",
    "mochawesome-merge": "^2.0.0",
    "mochawesome-report-generator": "^4.0.0",
  } 
```
Try updating your packeges and then executing the following commands
```
combine-reports:
	npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json

generate-report:
	npx marge mochareports/report.json -f report -o mochareports
```
Referenced from [here](https://github.com/YOU54F/cypress-slack-reporter/issues/69)

**Comment by deane187** [comment]
@ezra-m 
Below is my reporter options:
```
{
  "reporterEnabled": "mocha-junit-reporters, mochawesome",
  "mochaJunitReportersReporterOptions": {
    "mochaFile": "cypress/reports/junit/test_results[hash].xml",
    "toConsole": false
  },
  "mochawesomeReporterOptions": {
    "reportDir": "cypress/reports/mocha",
    "quiet": true,
    "overwrite": false,
    "html": false,
    "json": true
  }
}
```

**Comment by Antontelesh** [comment]
@ezra-m try updating to mochawesome@4 and mochawesome-merge@2

Version 1 is no longer supported.

**Comment by Antontelesh** [comment]
From your error message it looks like you get this not when running `mochawesome-merge` but when trying to generate the report with `mochawesome-report-generator` (marge). And the message says that marge expects the new structure introduced in v4 while you're supplying it the old structure from the version 3.

**Comment by ezra-m** [comment]
Thank you all, updating to mochawesome@4 and mochawesome-merge@2 worked perfectly.

**Comment by xwen-winnie** [comment]
> Thank you all, updating to mochawesome@4 and mochawesome-merge@2 worked perfectly.

my dep version is:
  "devDependencies": {
    "cypress": "^4.1.0",
    "mocha": "^6.2.2",
    "mocha-multi-reporters": "^1.1.7",
    "mochawesome": "^4.1.0",
    "mochawesome-merge": "^2.1.0",
    "mochawesome-report-generator": "^4.1.0"
  },
>npx marge mochawesome.json -f report -o mochareports
  error:
    supplied to /suites: Nil
    Invalid value 2020 supplied to /copyrightYear: Nil


and this issue still exsits, please help me check which version I should use? Thanks

**Comment by Antontelesh** [comment]
> "mochawesome-merge": "^2.1.0",

@xwen-winnie it seems you’re still using version 2. It’s no longer supported. Please migrate to v4
