### ISSUE TITLE
exec `npx mochawesome-merge --reportDir cypress/results > mochawesome.json` errror

### ISSUE THREAD

**Issue by chenhaizhou** [Antontelesh/mochawesome-merge#19]
**console error:**
```
ERROR: Failed to merge reports

TypeError: Cannot read property 'filter' of undefined
    at report (/Users/hzchen/.npm/_npx/50704/lib/node_modules/mochawesome-merge/lib/index.js:44:18)
    at Array.map (<anonymous>)
    at items (/Users/hzchen/.npm/_npx/50704/lib/node_modules/mochawesome-merge/lib/utils.js:3:46)
    at merge (/Users/hzchen/.npm/_npx/50704/lib/node_modules/mochawesome-merge/lib/index.js:57:18)
    at <anonymous>
```

**cypress.json:**
 ```
{
"reporter": "mochawesome",
  "reporterOptions": {
    "reportDir": "cypress/results",
    "overwrite": false,
    "html": false,
    "json": true
  }
}
```

**package.json:** 
   "cypress": "^3.3.1",
    "cypress-cucumber-preprocessor": "^1.11.2",
    "cypress-promise": "^1.0.2",
    "mocha": "^5.2.0",
    "mochawesome": "^3.0.3",

**Comment by Antontelesh** [comment]
@chenhaizhou What version of `mochawesome-merge` do you use?

**Comment by chenhaizhou** [comment]
> @chenhaizhou What version of `mochawesome-merge` do you use?

I use `npx`, should be the latest version.

**Comment by Antontelesh** [comment]
The latest mochawesome-merge does not support mochawesome@3.
Please, update mochawesome to version 4 and try again.

**Comment by chenhaizhou** [comment]
I updated mochawesome version to '4.0.1', but still has this issue.
