### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by vrodnyanskiy** [Antontelesh/mochawesome-merge#21]
Hi, 
When I try to merge reports I'm getting:
ERROR: Failed to merge reports

TypeError: Cannot read property 'filter' of undefined
    at report (/cypress/node_modules/mochawesome-merge/lib/index.js:44:18)
    at Array.map (<anonymous>)
    at items (/cypress/node_modules/mochawesome-merge/lib/utils.js:3:46)
    at merge (/cypress/node_modules/mochawesome-merge/lib/index.js:57:18)

The error does not make sense to me.
Any help will be greatly appreciated.
The command I use:
npx mochawesome-merge --reportDir reports > result.json

There are my json reports: 
[reports.zip](https://github.com/Antontelesh/mochawesome-merge/files/3475202/reports.zip)

**Comment by Antontelesh** [comment]
Hi @vrodnyanskiy. I suppose, if you are using `npx` then you’re probably using the latest version of `mochawesome-merge`, which works only with reports generated by the version 4 of `mochawesome`.

What version on mochawesome do you use to generate reports?

**Comment by vrodnyanskiy** [comment]
Hi @Antontelesh, thank you so much for the quick reply. Yes you were right, my mochawsom was quite old. 
This are versions that are working fine for me:
"mocha": "^5.2.0",
"mocha-multi-reporters": "^1.1.7",
"mochawesome": "^4.0.1",
"mochawesome-merge": "^2.0.1",
"mochawesome-report-generator": "^4.0.1",

please note, that mocha version is 5.2.0 where the latest one is 6.2 (I had to downgrade as reports were not working)

Thanks again for your help.
