### ISSUE TITLE
Merged suites with emtpy title

### ISSUE THREAD

**Issue by heliocor** [Antontelesh/mochawesome-merge#22]
When merging from mochawesome.json, mochawesome_001.json, ... to single file, only the first suite (coming from mochawesome.json) has the title node with information; all other suites structures (coming from mochawesome_001.json, 002, ...) are with the title node empty.

Checked all individual mochawesome jsons, and their suite node contains title with information.

Thanks !

**Comment by Antontelesh** [comment]
Thanks for reporting, @heliocor .
I currently don’t have time on investigating this deeply, but looks like an issue.

Would be happy if you open a PR with a repro or a fix.

**Comment by Antontelesh** [comment]
@heliocor which version of mochawesome-merge do you use?

**Comment by heliocor** [comment]
Managed to traverse the json suites structures successfully. Seems an issue of the mochawesome reporter module generating empty suites. So not a mochawesome-merge issue, will close. Thanks for your quick response.
