### ISSUE TITLE
mochawesome-merge command issue - (\lib\index.js:44:18)

### ISSUE THREAD

**Issue by aidanhyland** [Antontelesh/mochawesome-merge#23]
Hey Guys, 

Just wondering if you saw this issue before? Following a course but busted at the merge report stage.. I've all the pre-steps set up. Tried updating and downgrading the packages to no luck

npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json
ERROR: Failed to merge reports

TypeError: Cannot read property 'filter' of undefined
    at report ...Documents\cypressUdemy\node_modules\mochawesome-merge\lib\index.js:44:18)

 "devDependencies": {
    "cypress": "^3.4.1",
    "cypress-multi-reporters": "^1.2.1",
    "cypress-xpath": "^1.4.0",
    "mocha": "^6.1.4",
    "mochawesome": "^4.0.0",
    "mochawesome-merge": "^2.0.1",
    "mochawesome-report-generator": "^4.0.1",
    "moment": "^2.24.0"
  },

Any help would be appreciated.

Aidan

**Comment by Antontelesh** [comment]
@aidanhyland can you share an example of your source report files?

According to the error message it seems like your report does not have `results` property, but that may not be the root cause.

**Comment by aidanhyland** [comment]
@Antontelesh Thanks for your quick reply. I was able to clean the JSON files and run the commands a little differently. Now the index.js error no longer shows..

Use Case - One *json spec output.

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       16/10/2019     12:57          11497 mochawesome.json

1. Run "npx mochawesome-merge --reportDir ./cypress/reports/mocha/ > ./cypress/reports/mocha/report.json"

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       16/10/2019     12:57          11497 mochawesome.json
-a----       16/10/2019     12:58          23474 report.json

2. I do get a " Unexpected token � in JSON at position 0" when I run the 'npx marge ./cypress/reports/mocha/report.json' command. The report.json is identical to the mochawesome.json output

I saw you fixed this previously?

**Comment by prudhvidandamudi** [comment]
@aidanhyland  @Antontelesh 

I am also getting the same issue when i using 'npx mochawesome-report-generator' commands to generate the HTML. I also see there are multiple bugs created in the cypress github repo.
what is the solution for this?? how did you resolved it?

![image](https://user-images.githubusercontent.com/46937269/67399640-848a9280-f57a-11e9-9008-5d193aa6eb2c.png)
