### ISSUE TITLE
Output location no longer configurable with v4.0.0

### ISSUE THREAD

**Issue by xMutaGenx** [Antontelesh/mochawesome-merge#35]
After upgrading to v4 I don't seem to be able to configure the output location anymore.

Previously `reportDir` option would also specify where the reports go after the merge

Old:
```js
const options = {
        reportDir: 'anything'
    };
```
Would result in: `anything/mochawesome.html`

New:
```js
const options = {
        files: 'anything/*.json'
    };
```
Would result in: `mochawesome-report/mochawesome.html`

**Comment by Antontelesh** [comment]
Do you use CLI or JavaScript API?

**Comment by Antontelesh** [comment]
Also, `files` should be array

**Comment by Antontelesh** [comment]
JS module never generated a file for you, it returns a promise with the final report. You are free to use it however you want.

CLI tool never generated any file either. It was always printing the output to `stdout` and you as a consumer could pipe it into a file if you wanted. This logic remains the same in v4.

**Comment by xMutaGenx** [comment]
Ah sorry, yes, `files` is an array in the code, just free-hand mistake there! And, I'm using a js api

**Comment by xMutaGenx** [comment]
```js
const options = {
        files: [`${reportDir}/mochawesome_*.json`]
    };

    merge(options).then(report => create(report, options));
```

**Comment by xMutaGenx** [comment]
Ah sorry, found the issue, thanks!
