### ISSUE TITLE
Issue while running mochawesome-merge

### ISSUE THREAD

**Issue by ujwaldhakal** [Antontelesh/mochawesome-merge#39]
my dependencies

```
 "mocha": "5.2.0",
    "mochawesome": "^4.1.0",
    "mochawesome-merge": "^4.0.0",
    "mochawesome-report-generator": "^4.1.0",
```
```
"merge-report": "npx mochawesome-merge --reportDir cypress/reports",
    "after:tests": "npm run merge-report; npx marge cypress/reports/mochawesome.json"
```
while running after:tests

it throws 
```
 Invalid value null supplied to /stats/passPercent: Number
  Invalid value null supplied to /stats/pendingPercent: Number
  Invalid value false supplied to /results/0: Suite
```

**Comment by Antontelesh** [comment]
@ujwaldhakal, there’s no `reportDir` option in mochawesome-merge v4.

**Comment by ujwaldhakal** [comment]
Hi anto i still get
 ERROR: Failed to merge reports

{ Error: EISDIR: illegal operation on a directory, read errno: -21, code: 'EISDIR', syscall: 'read' }

previously it was working but with 4 its not working

**Comment by Antontelesh** [comment]
can you send me an example how do you invoke `mochawesome-merge`

**Comment by ujwaldhakal** [comment]
```
 "scripts": {
    "merge-report": " npx mochawesome-merge --reportDir cypress/reports",
    "after:tests": "npm run merge-report; npx marge cypress/reports/mochawesome.json"
  },
```
some point it will trigger merge-report from package.json and invokes this one

**Comment by Antontelesh** [comment]
cypress/reports is a directory, mochawesome-merge works with files and glob patterns. You need to specify the path to all your source files by listing them all or using a glob pattern:

```
npx mochawesome-merge cypress/reports/*.json
```

**Comment by ujwaldhakal** [comment]
Thanks
