### ISSUE TITLE
Do I need to have /mochawesome-report folder at root level can I customise it to be inside cypress/results/mochawesome-report

### ISSUE THREAD

**Issue by deshdeep-airwallex** [Antontelesh/mochawesome-merge#5]
Further information is requested

(node:83909) UnhandledPromiseRejectionWarning: Error: Directory /Users/deshdeep/XXXXX/mochawesome-report does not exist

**Comment by Antontelesh** [comment]
Hi, mochawesome allows to configure report directory via `reportDir` property.

Closing this as this is not related to mochawesome-merge
