### ISSUE TITLE
Question: Does this preserve the cli options passed to marge?

### ISSUE THREAD

**Issue by tnrich** [Antontelesh/mochawesome-merge#55]
Hey there,

Just wondering if I run 
```
marge --no-showPassed --no-showPending -o ./test-report 
```
and then use `mochawesome-merge` to merge it with another test report that also has the same CLI flags, 

will that preserve the `--no-showPassed` and `--no-showPending` flags?

Thanks @Antontelesh

**Comment by Antontelesh** [comment]
Hey @tnrich , I don't think I understand the question. `mochawesome-merge` command does not have anything in common with the `marge` one. They're completely separate CLI commands

**Comment by Antontelesh** [comment]
How does `--no-showPassed` affects the report JSON?

**Comment by tnrich** [comment]
Hey @Antontelesh --no-showPassed defaults the ui to not showing passed tests. I tried passing it to the marge commands being merged by mochawesome-meege and it seemed to work! So we're good 👍

**Comment by Antontelesh** [comment]
Thank you for confirmation, @tnrich
