### ISSUE TITLE
Inconvenient usage for HTML generation

### ISSUE THREAD

**Issue by rkrisztian** [Antontelesh/mochawesome-merge#56]
I've been following this guide (the CLI way):
https://www.npmjs.com/package/mochawesome-merge#cypress
But it puts report files all over the place. I'd like all files ideally be in `cypress/results`. For example like this:

```bash
RESULTS_DIR=cypress/results

mochawesome-merge $RESULTS_DIR/mochawesome*.json --output $RESULTS_DIR/all.json
marge --reportDir $RESULTS_DIR --reportFilename mochawesome.html $RESULTS_DIR/all.json
```

As you could see, I had to add quite some additional code so that the end result is still `mochawesome.html`. Partly because `mochawesome` does not follow a unique naming for the JSON files, that is, the first file isn't numbered. Ideally I would like to have a command like this:

```bash
# Dream command that fits into `package.json` as a post-script:
mochawesome-merge cypress/results/*.json --saveHtml --reportDir cypress/results
```

(Something like that, whatever fits best to the tool.)

Could you please provide us with something like that? Thanks in advance.

**Comment by Antontelesh** [comment]
Generating html is a responsibility of mochawesome report generator (marge).

mochawesome-merge exists to combine several json reports into one.

I would recommend you to split these two tasks into two commands if one command does not look beautiful for you
