### ISSUE TITLE
Error when running mochawesome-merge (Unexpected Token)

### ISSUE THREAD

**Issue by aviral2311** [Antontelesh/mochawesome-merge#6]
/node_modules/mochawesome-merge/lib/index.js:9
const Suite = ({ root, tests = [], suites, ...rest }) => {
                                           ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

I am stuck at this error when I am running mochawesome-merge with sdk as well as using cli as well. 
Could you please help me exactly what is going on

**Comment by mass85** [comment]
I have the same problem. It seems like mochawesome-merge requires transpilation.

**Comment by aviral2311** [comment]
@mass85 So what would you suggest to fix this?

**Comment by mass85** [comment]
Publish this package transpiled or rewrite code in a way compatible with node v6.

**Comment by Antontelesh** [comment]
Guys, what stops you from using `node@8`?

Official support for `node@6` ends in one month, and I don’t want legacy engine to force me changing the code.

**Comment by mass85** [comment]
Platform I am developing for has v6. However it will be updated soon.

Can you confirm that this problem will not reproduce in v8?

**Comment by aviral2311** [comment]
@Antontelesh I am using Node version 8.2.1

**Comment by Antontelesh** [comment]
node@8 has support for ES2015 features used in the code - const, arrow functions and destructuring: https://node.green

I’m going to set this in “engines” property in package.json

**Comment by Antontelesh** [comment]
BTW, tests on CircleCI for this package run in node@8

**Comment by mass85** [comment]
@Antontelesh mochawesome-merge uses object spread properties, which is supported starting from 8.6.0 according to https://node.green/#ES2018-features-object-rest-spread-properties-object-spread-properties. So your update https://github.com/Antontelesh/mochawesome-merge/pull/7/files is not precise.

**Comment by Antontelesh** [comment]
Now it’s precise. Thank you, @mass85

**Comment by lrQA** [comment]
Hello, 
I am seeing this same error (Unexpected token � in JSON at position 0) in version ^1.0.7 running Node LTS (10.14.1). 
Odd thing is, if I create a new file using VSCode then copy and paste the same content between files it works. 
Any suggestions?

**Comment by Antontelesh** [comment]
@lrQA this looks like a completely separate issue. Please check the JSON generated by mochawesome-merge. Does it contain proper encoding?

**Comment by lrQA** [comment]
@Antontelesh yes the JSON generated by mochawesome-merge does have proper encoding when verified at https://jsonlint.com/ and seems to be something with the file itself. Also note, this is only when generating a file from the command line using redirect to file (>).
When done in JavaScript the error does not persist.

**Comment by Antontelesh** [comment]
I believe it has to do with how “>” operator works on your system.

I was thinking that it saves the file with improper encoding (not utf-8), and when marge tries to read it as utf-8, it fails.

You can try putting a console.log statement in marge code, right before it tries to parse JSON, to check file contents.

**Comment by idxrx** [comment]
File contents is ok, but file format is not on Windows. Opening the merged json file in notepad++ shows it is encoded in UCS-2 LE BOM. Opening the file in a binary editor file starts with FF FE. That is why the error is Unexpected token � in JSON at position 0. Please change the saved file format. So npx mochawesome-report-generator mochawesome.json wont generate the unexpected token error.

**Comment by aidanhyland** [comment]
> File contents is ok, but file format is not on Windows. Opening the merged json file in notepad++ shows it is encoded in UCS-2 LE BOM. Opening the file in a binary editor file starts with FF FE. That is why the error is Unexpected token � in JSON at position 0. Please change the saved file format. So npx mochawesome-report-generator mochawesome.json wont generate the unexpected token error.

Did you get this working @idxrx ?

**Comment by muellercornelius** [comment]
Can confirm, the Problem only exists when using the wrong encoding. **Changing it to UTF-8 works** (not UTF-8 Bom)

**Comment by swathisham** [comment]
> Can confirm, the Problem only exists when using the wrong encoding. **Changing it to UTF-8 works** (not UTF-8 Bom)

How to change it to UTF-8?

**Comment by Ivan-Cristian** [comment]
> How to change it to UTF-8?

@swathisham and anybody else who is encountering this issue, you can do something like this: 

1. Create a file called encode.js:
```javascript
var fs = require('fs');
var file = fs.readFileSync('./cypress/reports/mochawesome.json', 'ucs2');
fs.writeFileSync('./cypress/reports/mochawesome.json', file, 'utf8');
```

2. Create a script to run the following the following:

```powershell
npx mochawesome-merge cypress/reports/mochawesome/mochawesome*.json > cypress/reports/mochawesome.json

node encode.js

$fileLocation = Join-Path (Get-Item -Path "cypress\reports").FullName "mochawesome.json"
$MyFile = Get-Content $fileLocation
[System.IO.File]::WriteAllLines($fileLocation, $MyFile)

npx mochawesome-report-generator --reportDir ./ --cdn true --charts true cypress/reports/mochawesome.json
```


Replace paths with whatever you have, and the middle 3 PowerShell lines with `sed -i '1s/^\xEF\xBB\xBF//' .\cypress\reports\mochawesome.json` if you're on a system that doesn't support PowerShell scripts, the sed command removes the BOM just the same

**Comment by mstephano** [comment]
It seams the problem is only with Windows. Following @Ivan-Cristian idea about an encode.js file, here is my code tomake it work:

```
// put this in encode.js file
// change 'mochawesome.json' to your relative path of mochawesome.json file

var isWin = process.platform === 'win32'

if (isWin) {
  var fileEncoding = getFileEncoding('mochawesome.json')
  var fs = require('fs')
  var data = fs.readFileSync('mochawesome.json', fileEncoding)
  data = data.toString('utf8').replace(/^\uFEFF/, '') // remove BOM
  fs.writeFileSync('mochawesome.json', data, 'utf8')
}

function getFileEncoding(f) {
  // this method is from https://stackoverflow.com/a/56188301
  var fs = require('fs')
  var d = new Buffer.alloc(5, [0, 0, 0, 0, 0])
  var fd = fs.openSync(f, 'r')
  fs.readSync(fd, d, 0, 5, 0)
  fs.closeSync(fd)

  // https://en.wikipedia.org/wiki/Byte_order_mark
  var e = false
  if (!e && d[0] === 0xef && d[1] === 0xbb && d[2] === 0xbf) e = 'utf8'
  if (!e && d[0] === 0xfe && d[1] === 0xff) e = 'utf16be'
  if (!e && d[0] === 0xff && d[1] === 0xfe) e = 'utf16le'
  if (!e) e = 'ascii'

  return e
}
```

Then run the command line to remove BOM: `node encode.js`

Then you can run the marge command to create the report: `npx marge mochawesome.json`

**Comment by Asad12** [comment]
> > How to change it to UTF-8?
> 
> @swathisham and anybody else who is encountering this issue, you can do something like this:
> 
> 1. Create a file called encode.js:
> 
> ```js
> var fs = require('fs');
> var file = fs.readFileSync('./cypress/reports/mochawesome.json', 'ucs2');
> fs.writeFileSync('./cypress/reports/mochawesome.json', file, 'utf8');
> ```
> 
> 1. Create a script to run the following the following:
> 
> ```powershell
> npx mochawesome-merge cypress/reports/mochawesome/mochawesome*.json > cypress/reports/mochawesome.json
> 
> node encode.js
> 
> $fileLocation = Join-Path (Get-Item -Path "cypress\reports").FullName "mochawesome.json"
> $MyFile = Get-Content $fileLocation
> [System.IO.File]::WriteAllLines($fileLocation, $MyFile)
> 
> npx mochawesome-report-generator --reportDir ./ --cdn true --charts true cypress/reports/mochawesome.json
> ```
> 
> Replace paths with whatever you have, and the middle 3 PowerShell lines with `sed -i '1s/^\xEF\xBB\xBF//' .\cypress\reports\mochawesome.json` if you're on a system that doesn't support PowerShell scripts, the sed command removes the BOM just the same

where to create encode.js file and how node script will pick it

**Comment by vladlearns** [comment]
If you want to do the same in PS:

```
npx mochawesome-merge cypress/reports/mocha/*.json > cypress/reports/mochareports/mochawesome.json
$content = Get-Content -Path cypress/reports/mochareports/mochawesome.json -Encoding Unicode
Set-Content -Path cypress/reports/mochareports/combinedReport.json -Value $content -Encoding UTF8
```
