### ISSUE TITLE
First mochawesome test appears in last position after merge

### ISSUE THREAD

**Issue by nitramL** [Antontelesh/mochawesome-merge#60]
After running my tests with cypress, I'm having a set of mochawesome files, called `mochawesome.json`, `mochawesome_001.json`, `mochawesome_002.json` etc...
Then, when I use `mochawesome-merge` to merge all this files, the result corresponding to the first test (chronologically), i.e. the one contained in `mochawesome.json`, appears in last position.
And then when I generate my report with `mochawesome-report-generator`, this first test still appears as the last test while I'd like to see it first.

Is there a way for the `mochawesome.json` file to be considered as the first file during merge? 
Or should I rename it as `mochawesome_000.json` before merging?
Or am I doing something wrong?

Here are my dependencies :
```
"mocha": "^8.2.1",
"mochawesome": "^6.2.1",
"mochawesome-merge": "^4.2.0",
"mochawesome-report-generator": "^5.1.0",
```

**Comment by Antontelesh** [comment]
Hey, @nitramL.
I think renaming would do the trick.
Also, you can try to specify it as the first in the list of input files.

In JS API it would look like this:
```js
merge({
  files: [
    'mochawesome.json',
    ‘mochawesome_*.json',
  ],
})
```

or using CLI:
```
mochawesome-merge mochawesome.json mochawesome_*.json -o output.json
```

**Comment by nitramL** [comment]
@Antontelesh you're right, that did the trick ! 👍 

Thanks a lot.
