### ISSUE TITLE
Deprecated unused uuid

### ISSUE THREAD

**Issue by JanKanty** [Antontelesh/mochawesome-merge#76]
You are using a deprecated version of `uuid`. But as I checked everywhere the package is no longer in use. Maybe we can remove it so it won't pop up during `npm install`?

**Comment by Antontelesh** [comment]
Hey @JanKanty, I would love to accept a PR making this change.
Ideally, I would replace `uuid` with [`nanoid`](https://github.com/ai/nanoid)

**Comment by JanKanty** [comment]
@Antontelesh I would gladly do it but I don't see any usage of this package. I even downloaded repo to search through folders but there is no require for it. If I don't see it but there is please point it to me

**Comment by Antontelesh** [comment]
@JanKanty can you try to remove this dependency? I don’t see it’s being used either

**Comment by JanKanty** [comment]
Do I have to update `yarn.lock` manually or it will update during release?

**Comment by JanKanty** [comment]
If not I made changes here: #78

**Comment by Antontelesh** [comment]
I’m not sure it will, so let’s commit it as well

**Comment by Antontelesh** [comment]
@JanKanty thank you for your contribution!
