### ISSUE TITLE
Pending tests are counted as skipped

### ISSUE THREAD

**Issue by gabrielcaamano-ujet** [Antontelesh/mochawesome-merge#91]
Pending tests are accounted as skipped.

**Stack:**
```
    "mocha": "^9.2.2",
    "mochawesome": "^7.1.3",
    "mochawesome-merge": "^4.2.1",
    "cypress": "~10.11.0",
```

**Steps:**
1. Create tests on 3 different Cypress specs. Have 1 spec pass, the other fail at a before hook, and have the last one skipped with `it.skip`.
2. Use mochawesome-merge to merge the results.

**Expected result:**
The merged stats show 3 tests: 1 passed, 1 pending, 1 skipped.

**Actual result:**
The merged stats show 3 tests: 1 passed, 2 skipped.

Input files:
[mochawesome-input.zip](https://github.com/Antontelesh/mochawesome-merge/files/10189167/mochawesome-input.zip)

Current output after `npx mochawesome-merge *.json -o output.json`:
[output.json.zip](https://github.com/Antontelesh/mochawesome-merge/files/10189170/output.json.zip)

**Comment by Antontelesh** [comment]
Hi @gabrielcaamano-ujet. Although, I may be able to take a look at this in some time, but would prefer if you create a PR with the fix and updated tests (at least test data) to cover the changes.

I will be happy to assist you by reviewing it and releasing the fix

**Comment by gabrielcaamano-ujet** [comment]
Hi @Antontelesh I have just created the new PR
